language: "ko-KR"
reviews:
  profile: "chill"
  review_status: true
  auto_review:
    enabled: true
  instructions: |
    모든 코드 리뷰는 반드시 한국어로 작성해주세요.
    불필요한 영어 설명은 피하고, 한국어 기술 용어를 우선 사용하세요.

    리뷰 시 다음을 중점적으로 봐주세요:
    - React 컴포넌트 구조의 적절성
    - 상태 관리 및 props 전달의 명확성
    - TypeScript 타입 안정성 (any 사용 지양)
    - 예외 처리 및 에러 핸들링의 일관성
    - API 통신 및 데이터 처리의 효율성
    - 코드의 존재 및 신뢰성
    - 코드의 가독성 및 유지보수성
